# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'ru-ru'

# Website info
name: 'Личный блог об азартных играх'
description: "В моем блоге Вы можете найти советы как играть в онлайн-казино, покере, и т.д"

short_url: 'http://www.bogenschuetzen-unterroth.info/'
google_analytics: 
disqus: username
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: http://www.bogenschuetzen-unterroth.info/

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag

# gems and other configs
gems:
  - "jekyll-minifier"
  - "jekyll-paginate"
  - "jekyll-sitemap"
  
plugins: 
  - jekyll-minifier
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives
    
# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: calmmoney
repo: calmmoney
branch: master
relative_source: ../calmmoney/
destination: ../calmmoney/
production_url:  https://calmmoney.github.io/
source_url:  https://calmmoney.github.io/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - node_modules
  - .git
